# Generated by Django 4.1.13 on 2024-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeedetail_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
