# Generated by Django 4.1.13 on 2024-02-26 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_employee_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_leave',
            new_name='EmployeeLeave',
        ),
    ]
